services:
  experiences-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/server/src
      - ./config.env:/server/config.env
    command: sh -c "npm run build && npm start"
